languageCode = "id"
languageName = "Indonesian"
weight = 1

title = "Alif Nuryana"

[params]
  isoCode = "id"
  displayName = "🇬🇧"
  rtl = false

  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "My Personal Website"

[author]
  name = "Alif Nuryana"
  image = "img/profile1.jpg"
  headline = "welcome to my digital playground 👋"
  bio = "I do things sometimes, and then I question why."
   links = [
     { email = "mailto:nuryana.alif@hotmail.com" },
     { github = "https://github.com/alifnuryana" },
     { instagram = "https://instagram.com/syntaxsavvy" },
     { twitter = "https://twitter.com/alifn27" },
   ]
